apiVersion: v1
kind: PersistentVolume
metadata:
  name: open5gs-mongodb-pv
spec:
  capacity:
    storage: 50Gi
  volumeMode: Filesystem
  accessModes:
    - ReadWriteOnce
    - ReadWriteMany
  persistentVolumeReclaimPolicy: Retain
  storageClassName: manual
  hostPath:
    path: /mnt/open5gs-mongodb-pv
