apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: open5gs-mongodb-claim
  namespace: open5gs
spec:
  storageClassName: manual
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 10Gi
