---
apiVersion: sriovnetwork.openshift.io/v1
kind: SriovNetworkNodePolicy
metadata:
  name: sriov-policy-node-2
  namespace: openshift-sriov-network-operator 
spec:
  # Resource name for pod scheduling
  resourceName: sriov_gnb_enp2s0
  nodeSelector:
    kubernetes.io/hostname: "node-2.example.com"
  priority: 10
  mtu: 9000
  numVfs: 16
  nicSelector: 
    # Directly targeting the enp2s0 physical interface
    pfNames: ["enp2s0#0-15"]
  # vfio-pci is required for high-performance gNB pod access
  deviceType: vfio-pci
  isRdma: false 
  needVhostNet: false 
---
apiVersion: sriovnetwork.openshift.io/v1
kind: SriovNetwork
metadata:
  name: sriov-ocudu
  namespace: openshift-sriov-network-operator 
spec:
  resourceName: sriov_gnb_enp2s0
  networkNamespace: ocudu
  vlan: 50
  spoofChk: "on"
  trust: "on"
  ipam: |
    {
      "type": "static"
    }
  linkState: "auto"
  capabilities: '{"mac": true, "ips": true}'
