apiVersion: lvm.topolvm.io/v1alpha1
kind: LVMCluster
metadata:
  name: lvmcluster
  namespace: openshift-storage
spec:
  storage:
    deviceClasses:
      - name: vg1
        # Match kds/bos2/base-config/90-lvmcluster.yaml: whole-disk paths fail if partition table exists.
        deviceSelector:
          paths:
            - /dev/nvme1n1p1
        thinPoolConfig:
          name: thin-pool-1
          overprovisionRatio: 10
          sizePercent: 90
